/*
 * This source file was generated by the Gradle 'init' task
 */
package the.last.commit;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    @Override
    public void start(Stage stage) {
        Label label = new Label(getGreeting());
        StackPane root = new StackPane(label);
        Scene scene = new Scene(root, 360, 240);

        stage.setTitle("JavaFX Demo");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
